name       : transgui
version    : 5.15.4
release    : 2
source     :
    - https://github.com/transmission-remote-gui/transgui/archive/v5.15.4.tar.gz : 37b08b15ae07ab26cb6a598c355e8e626b6877b8ee9fd00d2eccb0e03a02060f
license    : GPL-2.0-or-later
component  : network.download
summary    : A feature rich cross platform Transmission BitTorrent client
description: |
    Transmission Remote GUI is feature rich cross platform front-end to remotely control Transmission daemon via its RPC protocol. It is faster and has more functionality than builtin Transmission web interface.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - openssl-devel # for GeoIP flags
build      : |
    lazbuild "transgui.lpi" \
    --lazarusdir="/usr/share/lazarus" \
    --widgetset="gtk2" \
    --verbose
install    : |
    rm lang/transgui.template

    install -D -m 00755 units/transgui -t $installdir/usr/bin
    install -D -m 00644 lang/transgui.* -t $installdir/usr/share/transgui/lang
    install -D -m 00644 transgui.png -t $installdir/usr/share/pixmaps
    install -D -m 00644 $pkgfiles/transgui.desktop -t $installdir/usr/share/applications
