name       : transgui
version    : 5.18.0
release    : 6
source     :
    - https://github.com/transmission-remote-gui/transgui/archive/v5.18.0.tar.gz : d1cbb16eb35d41e76f4a171a3887053899e8dc6a1124afc21615b5038ea60d78
license    : GPL-2.0-or-later
component  : network.download
summary    : A feature rich cross platform Transmission BitTorrent client
description: |
    Transmission Remote GUI is feature rich cross platform front-end to remotely control Transmission daemon via its RPC protocol. It is faster and has more functionality than builtin Transmission web interface.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - openssl-11-devel # for GeoIP flags
build      : |
    lazbuild "transgui.lpi" \
    --lazarusdir="/usr/share/lazarus" \
    --widgetset="gtk2" \
    --verbose
install    : |
    rm lang/transgui.template

    install -D -m 00755 units/transgui -t $installdir/usr/bin
    install -D -m 00644 lang/transgui.* -t $installdir/usr/share/transgui/lang
    install -D -m 00644 transgui.png -t $installdir/usr/share/pixmaps
    install -D -m 00644 $pkgfiles/transgui.desktop -t $installdir/usr/share/applications
